name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
    
    - name: Check TypeScript types
      run: npx tsc --noEmit
    
    # TODO: Uncomment and configure when tests are added
    # - name: Run tests
    #   run: npm test
    
    - name: Build application
      run: |
        # Set default MongoDB URI if not provided
        if [ -z "$MONGODB_URI" ]; then
          export MONGODB_URI="mongodb://localhost:27017/soulscript-test"
        fi
        npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
